columns_map:
  name: 
    col_num: 3
    fill_missing: "NA"
  phone_number:
    col_num: 4
    fill_missing: None
  date_entered:
    col_num: 1
    fill_missing: None
  election_day:
    col_num: 24
    fill_missing: "NA"
  legal_background:
    col_num: 25
    fill_missing: "No"

inside:
  precinct_observer: inside_observer
  precinct_is_legal: inside_legal
  observer_availability: inside_all_day

outside_am:
  precinct_observer: outside_am_observer
  precinct_is_legal: outside_am_legal
  observer_availability: outside_AM

outside_pm:
  precinct_observer: outside_pm_observer
  precinct_is_legal: outside_pm_legal
  observer_availability: outside_PM

