observer_google_sheet: R5-Wake-Poll Observer Google Form (Responses)

columns_map:
  name: 
    col_num: 3
    fill_missing: "NA"
  phone_number:
    col_num: 4
    fill_missing: None
  date_entered:
    col_num: 1
    fill_missing: None
  election_day:
    col_num: 24
    fill_missing: "NA"
  legal_background:
    col_num: 25
    fill_missing: "No"
  post_code:
    col_num: 5
    fill_missing: 00000
  comments:
    col_num: 26
    fill_missing: ""

valid_post_codes: # from: https://www.zillow.com/browse/homes/nc/wake-county/
  - 27518
  - 27519
  - 27522
  - 27523
  - 27526
  - 27529
  - 27540
  - 27539
  - 27545
  - 27562
  - 27560
  - 27571
  - 27587
  - 27588
  - 27592
  - 27591
  - 27597
  - 27601
  - 27603
  - 27605
  - 27604
  - 27607
  - 27606
  - 27609
  - 27608
  - 27610
  - 27613
  - 27612
  - 27615
  - 27614
  - 27617
  - 27616
  - 27622
  - 27624
  - 27650
  - 27640
  - 27656
  - 27695
  - 27690
  - 27698
  - 27697
  - 27699
  - 27502
  - 27512
  - 27511
  - 27513

inside:
  from_county: True
  precinct_observer: 
   - inside_observer
  precinct_is_legal: inside_legal
  observer_availability: inside_all_day
  observer_loc: inside_location

outside_am:
  from_county: False
  precinct_observer: 
   - outside_am_observer
  precinct_is_legal: outside_am_legal
  observer_availability: outside_AM
  observer_loc: outside_am_location

outside_pm:
  from_county: False
  precinct_observer: 
   - outside_pm_observer
  precinct_is_legal: outside_pm_legal
  observer_availability: outside_PM
  observer_loc: outside_pm_location

outside_both:
  from_county: False
  precinct_observer: 
    - outside_pm_observer
    - outside_am_observer
  precinct_is_legal: 
    - outside_pm_legal
    - outside_am_legal
  observer_availability: outside_all_day
  observer_loc: outside_pm_location

